name: Package Python AWS Layer

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make layer.sh executable
        run: chmod +x layer.sh

      - name: Run layer.sh
        run: ./layer.sh

      - name: Upload layer artifact
        uses: actions/upload-artifact@v2
        with:
          name: layer-artifact
          path: aws-layer/$LAYER_NAME.zip
